version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on:
      - backend

  jenkins:
    image: custom-jenkins-with-docker
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - //./pipe/docker_engine://./var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

networks:
  jenkins:

volumes:
  jenkins_home:
